
import "./globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";
import { Poppins } from 'next/font/google';
import React from "react";
import AnimatedCursor from "react-animated-cursor"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // আপনি যেসব weight ব্যবহার করবেন
  variable: '--font-poppins', // Optional, CSS variable হিসেবে ব্যবহার করতে চাইলে
});
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body
      className="">
      <div className="">
        <AnimatedCursor 
         innerSize={20}
      outerSize={8}
      color='193, 11, 111'
      outerAlpha={0.6}
      innerScale={0.7}
      outerScale={8}/>
          <Navbar/>
        {children}
        <Footer/>
      </div>
      </body>
    </html>
  );
}
