
import "./globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";
import { Poppins } from 'next/font/google';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], 
  variable: '--font-poppins', 
});
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body
      className="">
      <div className="">
          <Navbar/>
        {children}
        <Footer/>
      </div>
      </body>
    </html>
  );
}
